package main

import (
	"os"
	"log"
	"github.com/urfave/cli"
)

func main() {
	app := cli.NewApp()
	app.Version = "1.0.0"
	app.Name = "Resource Parser"
	app.Usage = "Parse logs generated by analysis tool"
	app.Commands = []cli.Command{
		ParseCommand,
	}
	err := app.Run(os.Args)
	if err != nil {
		log.Fatal(err)
	}
}
